sudo: required

services:
  - docker

script:
  - |
    export IMAGE=cusspvz/nginx:latest &&
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker build -t ${IMAGE} . &&
    docker push ${IMAGE} &&
    exit 0 || exit 1

branches:
  only:
    - master
